apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-operator-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: su-instance-1/tenant-operator-config
    repoURL: 'https://github.com/stockholmuniversity/infra-gitops-config'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
